package com.trc.web.session;

public enum SessionKey {
	DEVICE_SWAP, DEVICE_RENAME, DEVICE_DEACTIVATE, DEVICE_REACTIVATE, DEVICE_ACCOUNT, DEVICE_ACCESSFEEDATE, DEVICE_ACCOUNTDETAIL, CREDITCARD_UPDATE, ENCRYPTER, TICKET, TICKET_NOTE;
}
