package com.trc.util.logger.activation;

public enum ActState {
  ROOT, RESERVE_PROFILE, INFO_CONTACT, INFO_DEVICE, INFO_PAYMENT, TEST_ACTIVATION, ACTIVATE_BILLING_ACCOUNT, ACTIVATE_PAYMENT, ACTIVATE_NETWORK_SERVICE, ACTIVATE_CREATE_SERVICE, ACTIVATE_ENABLE_USER, ACTIVATE_SAVE_USER, NOTIFY_WELCOME, HAS_COUPON, IS_COUPON_PAYMENT, APPLY_COUPON_PAYMENT, CHECK_COUPON_CONTRACT, APPLY_CONTRACT
}